Catlendar/catlendar-frontend

package-lock.json
package.json
src/App.tsx
src/components/Tab/Tab.styled.tsx
src/components/Tab/Tab.tsx
src/components/Tab/TabData.ts
src/components/Tab/TabTypes.ts
src/components/Toast/Toast.styled.tsx
src/components/Toast/Toast.tsx

1. Tab 컴포넌트 개발
2. TabData.ts 파일에 탭 메뉴 관리
3. TabTypes.ts 파일에 탭 타입 관리
1. Toast 컴포넌트 개발

✨ Feat : Tab컴포넌트, Toast 컴포넌트 

---

src/Styles/GlobalStyle.tsx
src/components/Calendar/ReactCalendar.style.tsx
src/components/Calendar/TodoCircle.style.tsx
src/components/Common/Modal/TodoListModal.tsx
src/index.tsx
src/pages/HomePage/HomePage.tsx

🐛Fix: fixed merge conflict

---

src/components/Common/DateInput/DateInput.styled.tsx
src/components/Common/DateInput/DateInput.tsx
src/components/DatePicker/DatePicker.tsx
src/pages/ApiPage.tsx
src/pages/SignupPage/UserInfoPage.tsx

✨ Feat: create DateInput

---

src/Styles/Calendar.css
src/components/Calendar/ReactCalendar.style.tsx
src/components/Calendar/ReactCalendar.tsx
src/components/Common/TodoBox/TodoBox.styled.tsx
src/components/Common/TodoBox/TodoBox.tsx
src/pages/CalendarPage/CalendarPage.tsx

- CalendarPage API 연동 및 구현
- ReactCalendar 컴포넌트 구현
- 비동기 처리 문제 해결
- 날짜 별로 일정을 분배하여 TodoCircle 스타일, 남은 개수 다르게 보여주기

✨ Feat: CalendarPage, ReactCalendar

---

src/api/Axios.tsx

add interceptor

---

src/assets/icons/icon-check.svg
src/components/Calendar/ReactCalendar.tsx
src/components/Calendar/TodoCircle.style.tsx
src/components/Common/TodoBox/TodoBox.tsx
src/pages/CalendarPage/CalendarPage.tsx
src/pages/HomePage/HomePage.tsx

- 해당 날짜의 남은 할일 표시 및 스타일링 
- 해당 날짜의 할일을 TodoBox와 연동
- 날짜에 따라 하단의 TodoBox 불러오기 수정
- 오늘의 경우 'today'로 api 호출
- 특정 날짜의 경우 'YYYY-MM-DD'로 api호출

✨ Feat: Calendar, TodoBox 

---

src/components/Common/TextInput/TextInput.styled.tsx
src/components/Common/TodoBox/TodoBox.tsx

🐛 Fix: commit error

---

src/components/Common/DateInput/DateInput.styled.tsx
src/components/Common/Modal/ModalLayout.styled.tsx
src/components/Common/Modal/TodoListModal/TodoModalList/BookmarkListItem/BookmarkToTodoButton.styled.tsx
src/components/Common/TextInput/TextInput.styled.tsx
src/components/DatePicker/DatePicker.styled.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/SignupPage/UserInfo.styled.tsx
src/pages/SignupPage/UserInfoPage.tsx

🎨 Style: Edit input, selectBox Style

---

netlify.toml

1. netlify.toml 생성
```
[build]
command = "CI= npm run build"
publish = "build"
```
3. npm install netlify-cli -g 설치

Config: netlify connect setting2

---

public/index.html

https 웹사이트에서 http request를 시도하면 에러 발생
해결방법 => http->https 요청 콘텐츠 변환

⚙️ Config: http->https 요청 콘텐츠 변환

---

src/components/Common/TodoBox/TodoList/TodoListItem/TodoListItem.tsx
src/pages/CalendarPage/CalendarPage.tsx
src/pages/HomePage/HomePage.tsx

🐛 Fix: commit conflict

---

src/atom/SelectTabTypeAtom.tsx
src/components/Common/Tab/Tab.styled.tsx
src/components/Common/Tab/Tab.tsx
src/components/Common/Tab/TabTypes.ts
src/pages/FortunePage/FortunePage.styled.tsx
src/pages/FortunePage/FortunePage.tsx
src/styles/GlobalStyle.tsx

:bug: Fix: 탭 UI  및 각 운세 탭 내용 더보기 상태 수정

---

.eslintrc.js
package-lock.json
package.json
src/App.tsx
src/components/Chart/ChartComponent.tsx
src/components/Common/TextInput/SelectInput.tsx
src/components/Common/TextInput/TextInput.styled.tsx
src/pages/CalendarPage/CalendarPage.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx

1. chart에 완료 api
2. select box 라이브러리 사용하여 모바일, pc 통일

✨ Feature chart.js, select library

---

src/pages/ProfilePage/EditPwPage.tsx
src/pages/ProfilePage/ProfileEditPage.tsx

✨ ProfileEdit, PWEdilt

---

src/components/Common/TextInput/SelectInput.tsx
src/pages/Router.tsx
src/pages/SignupPage/SignupPage.tsx

Fix URL route

---

src/pages/ProfilePage/EditPwPage.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/Router.tsx
src/pages/SettingPage/SettingPage.tsx

실서버에서 api 호출 이슈로 인해 router, navigate 수정

🐛 fix/ Router, navigate 수정

---

src/components/Common/Checkbox/Checkbox.tsx
src/components/Common/Modal/ReviseTodoModal.tsx
src/components/Common/Tab/Tab.tsx
src/components/Common/TextInput/TextInput.styled.tsx
src/components/Common/TextInput/TextInput.tsx
src/components/Common/TodoBox/TodoList/TodoListItem/ItemMenuButton.tsx
src/components/Common/TodoBox/TodoList/TodoListItem/TodoListItem.tsx

- Revise 모달 input 스타일 수정
- Checkbox 컴포넌트 onClick을 onChange로 수정

🎨 Style: Revise 모달 input 스타일 수정

---

src/components/Common/Button/HomeButton.tsx
src/components/Common/TodoBox/TodoBox.tsx
src/pages/Router.tsx

✨ Feat: landingPage

---

src/pages/LoginPage/LoginPage.tsx

🚚 Rename: test account 변경

---

src/components/Common/NavBar/NavBar.styled.tsx
src/components/Common/NavBar/NavBar.tsx
src/pages/FortunePage/FortunePage.styled.tsx

navbar버튼 클릭범위 확장, 오늘의 운세 배경색 통일

🎨 Style: navbar버튼 클릭범위 확장, 오늘의 운세 배경색 통일

---

src/components/Layout/Layout.styled.tsx
src/pages/FortunePage/FortunePage.tsx
src/pages/LandingPage/LandingPage.tsx
src/pages/LoginPage/LoginPage.styled.tsx

♻️ Refactor: 이미지 캐싱

---

src/components/Common/Button/Button.styled.tsx
src/components/Layout/Layout.styled.tsx
src/pages/LoginPage/LoginPage.styled.tsx
src/pages/LoginPage/LoginPage.tsx
src/pages/SignupPage/Signup.styled.tsx
src/pages/SignupPage/SignupPage.tsx

:bug: Fix: 버튼 구조 수정

---

src/components/Common/Tab/TabData.ts
src/pages/FortunePage/FortunePage.styled.tsx
src/pages/LandingPage/LandingPage.styled.tsx
src/pages/ProfilePage/ProfileEditPage.tsx

1. landingImg, FortuneImg size지정
2. 운세탭 내용 변경

♻️ Refactor: Img size지정, 운세탭 내용 변경

---

src/components/Common/DateInput/DateInput.styled.tsx
src/components/Common/TextInput/TextInput.styled.tsx

🎨 Style: Fixed inputName style

---

src/components/Common/TextInput/TextInput.styled.tsx
src/components/Layout/Layout.styled.tsx
src/pages/LandingPage/LandingPage.styled.tsx
src/pages/LandingPage/LandingPage.tsx
src/pages/LoginPage/LoginPage.styled.tsx
src/pages/LoginPage/LoginPage.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/Router.tsx
src/pages/SettingPage/SettingPage.styled.tsx
src/pages/SettingPage/SettingPage.tsx
src/pages/SignupPage/Signup.styled.tsx
src/pages/SignupPage/SignupCompletePage.styled.tsx
src/pages/SignupPage/SignupCompletePage.tsx
src/pages/SignupPage/SignupPage.tsx
src/pages/SignupPage/UserInfo.styled.tsx
src/pages/SignupPage/UserInfoPage.tsx
src/styles/GlobalStyle.tsx

landing, signup, login, settingPage 반응형작업

🎨 Style: 페이지별 반응형작업

---

src/components/MainCard/MainCard.styled.tsx
src/components/MainCard/MainCard.tsx
src/pages/HomePage/HomePage.tsx

- 해상도에 따라 MainCard의 margin 조정
- 데스크탑에서는 운세 링크 중복이라 안보이도록 설정

🐛 Fix: margin on MainCard

---

src/components/MainCard/MainCard.styled.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx
src/pages/ProfilePage/ProfilePage.tsx

🐛 Fix: 홈화면 오늘의운세 버튼 범위 수정

---

src/components/Common/DateInput/DateInput.styled.tsx
src/components/Common/DateInput/DateInput.tsx
src/components/Common/TextInput/SelectInput.tsx
src/components/Common/TextInput/TextInput.styled.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx
src/pages/SignupPage/UserInfo.styled.tsx
src/pages/SignupPage/UserInfoPage.tsx
src/styles/GlobalStyle.tsx

🎨 Style: 1920px 해상도 반응형작업

---

src/pages/SettingPage/SettingPage.styled.tsx

:lipstick: Style: 설정페이지 간격 조정

---

src/components/Common/NavBar/NavBar.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx
src/pages/ProfilePage/ProfilePage.tsx
src/pages/Router.tsx

- 프로필 페이지 반응형
1. /setting에서 화면 넓어지면 /profile로 이동
2. grid 사용
3. ChartComponent 크기는 scale(1.5)
- NavBar, '/' 경로에서 렌더링되지 않는 문제
1. NavBar 컴포넌트에서 path='/' 추가

🎨 Style: 프로필 페이지 반응형 작업

---

src/components/Common/TextInput/SelectInput.tsx

SelectINput.tsx 
Select의 customStyles에서 singleValue에 height : '2.4ren' 지정

🎨 Style : 내 정보 수정 페이지 양력, 태어난 시간, 선택시 텍스트 잘림 수정

---

src/components/Layout/Layout.styled.tsx

🎨 Style : Layout 스타일 수정

---

src/components/Layout/Layout.styled.tsx
src/pages/FortunePage/FortunePage.styled.tsx
src/pages/FortunePage/FortunePage.tsx

♻️ Refactor: 운세 더보기 버튼 삭제

---

src/components/Common/Modal/ModalLayout.styled.tsx
src/pages/ProfilePage/ProfilePage.styled.tsx
src/pages/SignupPage/UserInfoPage.tsx

1. birthTime, calendarType 기본값 지정
2. 회원탈퇴문구 및 텍스트 색 조정

♻️ Refactor: birthTime, calendarType 기본값 지정, 회원탈퇴문구 및 텍스트 색 조정

---

src/components/Chart/ChartComponent.tsx
src/components/Common/AddModalInput/AddModalInput.styled.tsx
src/components/Common/NavBar/HeaderNavbar.tsx
src/components/Common/NavBar/NavBar.tsx
src/components/Common/TextInput/SelectInput.tsx
src/components/Common/TodoBox/TodoBox.styled.tsx
src/components/Layout/Layout.styled.tsx
src/components/MainCard/MainCard.styled.tsx
src/pages/FortunePage/FortunePage.tsx
src/pages/HomePage/HomePage.tsx
src/pages/ProfilePage/ProfileEditPage.tsx
src/pages/Router.tsx
src/styles/GlobalStyle.tsx

responsive header-navbar featured

---

src/components/Common/TodoBox/TodoBox.styled.tsx
src/components/Layout/Layout.styled.tsx
src/components/MainCard/MainCard.styled.tsx
src/styles/GlobalStyle.tsx

:recycle: Refactor: 메인 페이지 반응형 리팩토링

---

src/components/Common/ErrorMessage/ErrorMessage.tsx

♻️ Refactor: 에러메세지 시간 증가
